function regen-shell-inits --description 'Regenerate the static init snapshots in conf.d (starship/zoxide/direnv/pyenv)'
    # These files in conf.d are committed snapshots of `<tool> init fish` output. Sourcing a
    # static file is much cheaper than running the tool's init on every shell start, but the
    # snapshots drift when the tools are upgraded. Run this after a `brew upgrade` (maintain
    # does it for you) to refresh them.
    set -l confd $HOME/.config/fish/conf.d

    set -l header \
        '# ==============================================================================' \
        '# GENERATED FILE - do not edit by hand.' \
        "# Static snapshot regenerated by \`regen-shell-inits\`." \
        '# =============================================================================='

    if command -q starship
        # --print-full-init inlines the whole init; plain `starship init fish` only emits a
        # dynamic bootstrap that re-runs starship at every startup, defeating the snapshot.
        starship init fish --print-full-init >$confd/starship_init.fish
        echo "🚀 starship_init.fish regenerated"
    end

    if command -q zoxide
        # --cmd cd makes zoxide replace `cd` itself (so plain `cd foo` gets the jump
        # behavior); without it zoxide only defines `z`/`zi` and leaves `cd` alone.
        zoxide init --cmd cd fish >$confd/zoxide_init.fish
        echo "📁 zoxide_init.fish regenerated"
    end

    if command -q direnv
        begin
            printf '%s\n' $header
            printf '%s\n' '# Snapshot of `direnv hook fish` - avoids spawning direnv on every shell start.'
            direnv hook fish
        end >$confd/direnv_hook.fish
        echo "🔀 direnv_hook.fish regenerated"
    end

    if command -q pyenv
        # The snapshot embeds the Cellar-versioned completions path, which is
        # exactly the kind of drift a post-upgrade regen (via maintain) fixes.
        # The snapshot hardcodes its own paths — it does not need PYENV_ROOT
        # (exported in config.fish, which loads after conf.d) at source time.
        begin
            printf '%s\n' $header
            printf '%s\n' '# Snapshot of `pyenv init - fish` - avoids spawning pyenv on every shell start.'
            pyenv init - fish
        end >$confd/pyenv_init.fish
        echo "🐍 pyenv_init.fish regenerated"
    end

    # NOTE: the mcfly snapshot was REMOVED along with mcfly itself. Its
    # Ctrl-R binding had been shadowed by fzf.fish's history search (bound
    # later, from config.fish) the whole time, while its fish_postexec hook
    # still spawned a `mcfly add` process after every command — and its
    # `exit 1` guards would have killed every new shell had the binary ever
    # gone missing. History search is fzf.fish's Ctrl-R.

    echo "✅ Shell init snapshots up to date."
end
