# =============================================================================
# fish_config --- Main configuration for the Fish Shell
# =============================================================================
#
# Commentary:
# This is the entry point for the Fish shell. It handles path setup, 
# environment variables, and interactive features like prompts and aliases.
#
# The file is split into two main parts:
# 1. Universal Setup: Always runs (important for GUI apps like Emacs).
# 2. Interactive Setup: Runs only when you are actually typing in a terminal.
# =============================================================================
# PLUGIN MANAGEMENT (FISHER)
# =============================================================================
set -gx fisher_path $HOME/.config/fish/plugins

if not contains $fisher_path/functions $fish_function_path
    set -gp fish_function_path $fisher_path/functions
end

if not contains $fisher_path/completions $fish_complete_path
    set -gp fish_complete_path $fisher_path/completions
end

for file in $fisher_path/conf.d/*.fish
    if test -f $file
        source $file
    end
end

if status is-interactive; and not type -q fisher
    echo "🎣 Fisher not found. Bootstrapping..."
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher update
end

# =============================================================================
# 1. CORE ENVIRONMENT (PATH & VARIABLES)
# =============================================================================

set -g fish_greeting ""

# --- Fast Homebrew Initialization ---
# NOTE on MANPATH/INFOPATH: the trailing '' element exports a trailing colon
# (e.g. "/opt/homebrew/share/man:"), which tells man/info "ALSO search the
# system defaults". Without it, setting MANPATH at all makes it exclusive —
# `man ls` and every other system man page silently stopped resolving.
# (`brew shellenv` emits the same trailing colon for the same reason.)
if test -d /opt/homebrew # Apple Silicon
    set -gx HOMEBREW_PREFIX /opt/homebrew
    set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
    set -gx HOMEBREW_REPOSITORY /opt/homebrew
    fish_add_path -g /opt/homebrew/bin /opt/homebrew/sbin
    set -gx MANPATH /opt/homebrew/share/man $MANPATH ''
    set -gx INFOPATH /opt/homebrew/share/info $INFOPATH ''
else if test -d /usr/local/Homebrew # Intel Mac
    set -gx HOMEBREW_PREFIX /usr/local
    set -gx HOMEBREW_CELLAR /usr/local/Cellar
    set -gx HOMEBREW_REPOSITORY /usr/local/Homebrew
    fish_add_path -g /usr/local/bin /usr/local/sbin
    set -gx MANPATH /usr/local/share/man $MANPATH ''
    set -gx INFOPATH /usr/local/share/info $INFOPATH ''
end

# --- Homebrew Completions ---
if test -d "$HOMEBREW_PREFIX/share/fish/completions"
    set -p fish_complete_path "$HOMEBREW_PREFIX/share/fish/completions"
end
if test -d "$HOMEBREW_PREFIX/share/fish/vendor_completions.d"
    set -p fish_complete_path "$HOMEBREW_PREFIX/share/fish/vendor_completions.d"
end

# --- Custom PATH Additions ---
# $HOMEBREW_PREFIX, not a hardcoded /usr/local: works on both Intel and
# Apple Silicon (consistent with the dual-prefix detection above).
fish_add_path -g $HOMEBREW_PREFIX/opt/ruby/bin
# Gem bin dirs via glob, not a pinned "3.3.0": a ruby upgrade changes the
# directory name and a hardcoded version silently drops your gems from PATH.
# `for` is used because it tolerates an unmatched glob (zero iterations),
# whereas a bare failing glob would error out the fish_add_path call.
for dir in $HOME/.gem/ruby/*/bin
    fish_add_path -g $dir
end
fish_add_path -g $HOMEBREW_PREFIX/opt/grep/libexec/gnubin
fish_add_path -g $HOME/.cargo/bin
fish_add_path -g $HOME/.local/bin
fish_add_path -g "$HOME/Library/Application Support/Coursier/bin"

# Pyenv: the shims PATH entry and shell function come from
# conf.d/pyenv_init.fish — a cached snapshot of `pyenv init - fish`
# (regenerated by `maintain`), which hardcodes its paths, so it does not
# depend on this variable being set first (conf.d loads before this
# file). PYENV_ROOT is exported for pyenv itself and for tools that
# consult it (matches the default, kept explicit).
set -gx PYENV_ROOT $HOME/.pyenv

# Node (nvm.fish): put the default version's bin on PATH in EVERY shell.
# The plugin's own conf.d auto-activation is guarded by `status
# is-interactive`, so without this line non-interactive shells have no
# node at all — including the login shell exec-path-from-shell spawns
# for Emacs, which would silently lose node, npm, and every npm-installed
# language server. Interactive shells still run the plugin's `nvm use`
# on top; fish_add_path deduplicates. (Node was previously ALSO installed
# via Homebrew, which masked this gap; nvm is now the only runtime.)
if set -q nvm_default_version
    fish_add_path -g $HOME/.local/share/nvm/$nvm_default_version/bin
end

# Pyenv shims must WIN over Homebrew's own python3 in /usr/local/bin.
# conf.d/pyenv_init.fish prepends the shims at startup, but every
# fish_add_path call in this file runs AFTER conf.d and lands in front
# of them — leaving Homebrew's python3 shadowing pyenv's. --move pulls
# the (already-present) shims entry back to the front; keep this line
# below all other PATH additions in this file.
fish_add_path -gm $PYENV_ROOT/shims

# -t opens the buffer directly inside your terminal window (perfect for git commits)
# -a '' automatically starts the daemon in the background if it isn't running yet
set -gx EDITOR "emacsclient -t -a ''"

# VISUAL is used by some GUI-aware tools. -c opens a new graphical window.
set -gx VISUAL "emacsclient -c -a emacs"

# JAVA_HOME for Emacs.
# Use the version-stable brew `opt` symlink instead of spawning /usr/libexec/java_home
# on every shell start (~80ms). The opt symlink tracks brew upgrades automatically.
set -gx JAVA_HOME $HOMEBREW_PREFIX/opt/openjdk/libexec/openjdk.jdk/Contents/Home

# Direnv: the hook is cached as a static snapshot in conf.d/direnv_hook.fish
# (regenerated by `maintain`) so we don't spawn `direnv hook` on every shell start.

# Playwright downloads its browsers here; exported for GUI apps and scripts
# alike, so it lives in the universal section, not the interactive one.
set -gx PLAYWRIGHT_BROWSERS_PATH "$HOME/Library/Caches/ms-playwright"

# =============================================================================
# 2. INTERACTIVE-ONLY SETUP
# =============================================================================

if status is-interactive

    set -gx GPG_TTY (tty)

    # Syntax-highlighted man pages
    set -gx MANPAGER "bat -l man -p"

    # --- Starship Prompt ---
    # We keep this dynamic because it handles transience, but it's now the ONLY dynamic init
    if command -q starship
        function starship_transient_prompt_func
            starship module character
        end
        enable_transience
    end

    # -------------------------------------------------------------------------
    # BACKGROUND UPDATES
    # -------------------------------------------------------------------------
    read -l last_update <~/.brew_last_update 2>/dev/null; or set -l last_update ""
    set -l today (date +%Y-%m-%d)

    if test "$last_update" != "$today"
        nohup fish -c brew_daily_update >/dev/null 2>&1 &
    end

    # --- System Info ---
    # Fastfetch probes hardware (~210ms), so show it only on the FIRST real terminal
    # of a boot, not in every tab/split/subshell.
    #
    #   * `isatty stdout` gates out shells whose output is not a real terminal:
    #     Claude Code, Emacs comint shells, `fish -c` from scripts, pipes, etc. Those
    #     are interactive per `status is-interactive` and would otherwise claim the
    #     one-shot before you ever open a terminal window, leaving it blank for you.
    #   * The marker is keyed to the kernel boot time. $TMPDIR persists across reboots
    #     on macOS (only a ~3-day idle sweep clears it), so a plain marker would never
    #     reappear after a restart. Comparing against the boot time resets it exactly
    #     once per boot. The gate stays cheap: builtins (test/read/echo) plus one sysctl.
    if command -q fastfetch; and isatty stdout
        set -q TMPDIR[1]; or set -l TMPDIR /tmp
        set -l ff_marker $TMPDIR/.fastfetch_shown_$USER
        set -l boot (sysctl -n kern.boottime 2>/dev/null | string replace -rf '^\{ sec = (\d+).*' '$1')
        test -n "$boot"; or set boot unknown
        set -l seen ""
        test -e $ff_marker; and read seen <$ff_marker
        if test "$seen" != "$boot"
            echo $boot >$ff_marker
            fastfetch
        end
    end

    # -------------------------------------------------------------------------
    # ALIASES & ABBREVIATIONS
    # -------------------------------------------------------------------------
    alias python=python3
    abbr -a brewed 'brew bundle dump --file=~/dotfiles/homebrew/.Brewfile --force'
    # brewup = maintain. The old expansion (update/upgrade/cleanup + regen)
    # was a near-duplicate of `maintain` that skipped the Brewfile dump and
    # never stamped ~/.brew_last_update — so the background daily job would
    # redo the same work later that day. One maintenance path, not three.
    abbr -a brewup maintain

    if command -q eza
        alias ls='eza --icons'
        alias ll='eza -l --icons'
        alias lt='eza -T --icons'
    end

    if command -q bat
        alias cat='bat --paging=never'
    end

    # -------------------------------------------------------------------------
    # PLUGIN CONFIGURATIONS & THEME
    # -------------------------------------------------------------------------
    set -g puffer_fish_color 8ec07c
    # (A `__fish_abbreviation_tips_enable_on_command_execution` setting was
    #  removed here: the installed abbreviation-tips plugin only reads
    #  ABBR_TIPS_* variables — that line was a no-op.)

    set -g fish_color_normal ebdbb2
    set -g fish_color_command b8bb26
    set -g fish_color_quote d79921
    set -g fish_color_redirection d3869b
    set -g fish_color_end 83a598
    set -g fish_color_error fb4934
    set -g fish_color_param 8ec07c
    set -g fish_color_comment 928374
end
