# =============================================================================
# fish_config --- Main configuration for the Fish Shell
# =============================================================================
#
# Commentary:
# This is the entry point for the Fish shell. It handles path setup, 
# environment variables, and interactive features like prompts and aliases.
#
# The file is split into two main parts:
# 1. Universal Setup: Always runs (important for GUI apps like Emacs).
# 2. Interactive Setup: Runs only when you are actually typing in a terminal.
# =============================================================================
# PLUGIN MANAGEMENT (FISHER)
# =============================================================================
set -gx fisher_path $HOME/.config/fish/plugins

if not contains $fisher_path/functions $fish_function_path
    set -gp fish_function_path $fisher_path/functions
end

if not contains $fisher_path/completions $fish_complete_path
    set -gp fish_complete_path $fisher_path/completions
end

for file in $fisher_path/conf.d/*.fish
    if test -f $file
        source $file
    end
end

if status is-interactive; and not type -q fisher
    echo "🎣 Fisher not found. Bootstrapping..."
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher update
end

# =============================================================================
# 1. CORE ENVIRONMENT (PATH & VARIABLES)
# =============================================================================

set -g fish_greeting ""

# --- Homebrew ---
# Prefix detection (/opt/homebrew on Apple silicon, /usr/local on Intel),
# PATH, MANPATH/INFOPATH and completions live in conf.d/00-homebrew.fish.
# conf.d loads before this file, so $HOMEBREW_PREFIX is already set here --
# and, crucially, before the generated snapshots in conf.d that depend on it.

# --- Custom PATH Additions ---
# $HOMEBREW_PREFIX, not a hardcoded /usr/local: works on both Intel and
# Apple Silicon (consistent with the dual-prefix detection above).
fish_add_path -g $HOMEBREW_PREFIX/opt/ruby/bin
# Gem bin dirs via glob, not a pinned "3.3.0": a ruby upgrade changes the
# directory name and a hardcoded version silently drops your gems from PATH.
# `for` is used because it tolerates an unmatched glob (zero iterations),
# whereas a bare failing glob would error out the fish_add_path call.
for dir in $HOME/.gem/ruby/*/bin
    fish_add_path -g $dir
end
fish_add_path -g $HOMEBREW_PREFIX/opt/grep/libexec/gnubin
fish_add_path -g $HOME/.cargo/bin
fish_add_path -g $HOME/.local/bin
fish_add_path -g "$HOME/Library/Application Support/Coursier/bin"

# Pyenv: the shims PATH entry and shell function come from
# conf.d/pyenv_init.fish — a cached snapshot of `pyenv init - fish`
# (regenerated by `maintain`). The snapshot only depends on
# $HOMEBREW_PREFIX (set by conf.d/00-homebrew.fish, which sorts before
# it) and $HOME, not on this variable, so it does not matter that conf.d
# loads before this file. PYENV_ROOT is exported for pyenv itself and for
# tools that consult it (matches the default, kept explicit).
set -gx PYENV_ROOT $HOME/.pyenv

# Node (nvm.fish): put the default version's bin on PATH in EVERY shell.
# The plugin's own conf.d auto-activation is guarded by `status
# is-interactive`, so without this line non-interactive shells have no
# node at all — including the login shell exec-path-from-shell spawns
# for Emacs, which would silently lose node, npm, and every npm-installed
# language server. Interactive shells still run the plugin's `nvm use`
# on top; fish_add_path deduplicates.
#
# nvm is the ONLY Node runtime we manage. Homebrew may still carry a
# `node` formula as a transitive dependency of something else (currently
# agent-browser); because this fish_add_path runs after conf.d put
# $HOMEBREW_PREFIX/bin on PATH, nvm's bin lands in front and wins.
#
# nvm_default_version must be the CONCRETE version directory name
# (e.g. v24.21.0), not an alias like `lts`: the plugin resolves aliases,
# but this path does not. Set it with
#     set -U nvm_default_version (node --version)
# right after `nvm install lts` (which activates the version it installed).
if set -q nvm_default_version
    fish_add_path -g $HOME/.local/share/nvm/$nvm_default_version/bin
end

# Pyenv shims must WIN over Homebrew's own python3 in $HOMEBREW_PREFIX/bin.
# conf.d/pyenv_init.fish prepends the shims at startup, but every
# fish_add_path call in this file runs AFTER conf.d and lands in front
# of them — leaving Homebrew's python3 shadowing pyenv's. --move pulls
# the (already-present) shims entry back to the front; keep this line
# below all other PATH additions in this file.
fish_add_path -gm $PYENV_ROOT/shims

# -t opens the buffer directly inside your terminal window (perfect for git commits)
# -a '' automatically starts the daemon in the background if it isn't running yet
set -gx EDITOR "emacsclient -t -a ''"

# VISUAL is used by some GUI-aware tools. -c opens a new graphical window.
set -gx VISUAL "emacsclient -c -a emacs"

# JAVA_HOME for Emacs.
# Use the version-stable brew `opt` symlink instead of spawning /usr/libexec/java_home
# on every shell start (~80ms). The opt symlink tracks brew upgrades automatically.
set -gx JAVA_HOME $HOMEBREW_PREFIX/opt/openjdk/libexec/openjdk.jdk/Contents/Home

# Direnv: the hook is cached as a static snapshot in conf.d/direnv_hook.fish
# (regenerated by `maintain`) so we don't spawn `direnv hook` on every shell start.

# Playwright downloads its browsers here; exported for GUI apps and scripts
# alike, so it lives in the universal section, not the interactive one.
set -gx PLAYWRIGHT_BROWSERS_PATH "$HOME/Library/Caches/ms-playwright"

# CLIs that honor $BROWSER (aws sso login, gh auth login, ...) open URLs
# through the profile router instead of Chrome's last-used profile. Routing
# rules live in ~/.config/chrome-router/ (untracked); per-client .envrc
# files re-export the same value and select their context via CLIENT_NAME.
set -gx BROWSER $HOME/bin/chrome-route

# =============================================================================
# 2. INTERACTIVE-ONLY SETUP
# =============================================================================

if status is-interactive

    set -gx GPG_TTY (tty)

    # Syntax-highlighted man pages
    set -gx MANPAGER "bat -l man -p"

    # --- Starship Prompt ---
    # We keep this dynamic because it handles transience, but it's now the ONLY dynamic init
    if command -q starship
        function starship_transient_prompt_func
            starship module character
        end
        enable_transience
    end

    # -------------------------------------------------------------------------
    # BACKGROUND UPDATES
    # -------------------------------------------------------------------------
    # Guard with `test -f`: on a fresh machine the marker does not exist until
    # the first update completes, and fish warns about a failed `<file`
    # redirection on stderr regardless of `2>/dev/null`.
    set -l last_update ""
    if test -f ~/.brew_last_update
        read -l last_update <~/.brew_last_update
    end
    set -l today (date +%Y-%m-%d)

    if test "$last_update" != "$today"
        nohup fish -c brew_daily_update >/dev/null 2>&1 &
    end

    # --- System Info ---
    # Fastfetch probes hardware (~210ms), so show it only on the FIRST real terminal
    # of a boot, not in every tab/split/subshell.
    #
    #   * `isatty stdout` gates out shells whose output is not a real terminal:
    #     Claude Code, Emacs comint shells, `fish -c` from scripts, pipes, etc. Those
    #     are interactive per `status is-interactive` and would otherwise claim the
    #     one-shot before you ever open a terminal window, leaving it blank for you.
    #   * The marker is keyed to the kernel boot time. $TMPDIR persists across reboots
    #     on macOS (only a ~3-day idle sweep clears it), so a plain marker would never
    #     reappear after a restart. Comparing against the boot time resets it exactly
    #     once per boot. The gate stays cheap: builtins (test/read/echo) plus one sysctl.
    if command -q fastfetch; and isatty stdout
        set -q TMPDIR[1]; or set -l TMPDIR /tmp
        set -l ff_marker $TMPDIR/.fastfetch_shown_$USER
        set -l boot (sysctl -n kern.boottime 2>/dev/null | string replace -rf '^\{ sec = (\d+).*' '$1')
        test -n "$boot"; or set boot unknown
        set -l seen ""
        test -e $ff_marker; and read seen <$ff_marker
        if test "$seen" != "$boot"
            echo $boot >$ff_marker
            fastfetch
        end
    end

    # -------------------------------------------------------------------------
    # ALIASES & ABBREVIATIONS
    # -------------------------------------------------------------------------
    alias python=python3
    abbr -a brewed 'brew bundle dump --file=~/dotfiles/homebrew/.Brewfile --force'
    # brewup = maintain. The old expansion (update/upgrade/cleanup + regen)
    # was a near-duplicate of `maintain` that skipped the Brewfile dump and
    # never stamped ~/.brew_last_update — so the background daily job would
    # redo the same work later that day. One maintenance path, not three.
    abbr -a brewup maintain

    if command -q eza
        alias ls='eza --icons'
        alias ll='eza -l --icons'
        alias lt='eza -T --icons'
    end

    if command -q bat
        alias cat='bat --paging=never'
    end

    # -------------------------------------------------------------------------
    # PLUGIN CONFIGURATIONS & THEME
    # -------------------------------------------------------------------------
    set -g puffer_fish_color 8ec07c
    # (A `__fish_abbreviation_tips_enable_on_command_execution` setting was
    #  removed here: the installed abbreviation-tips plugin only reads
    #  ABBR_TIPS_* variables — that line was a no-op.)

    set -g fish_color_normal ebdbb2
    set -g fish_color_command b8bb26
    set -g fish_color_quote d79921
    set -g fish_color_redirection d3869b
    set -g fish_color_end 83a598
    set -g fish_color_error fb4934
    set -g fish_color_param 8ec07c
    set -g fish_color_comment 928374
end
