# ==============================================================================
# GENERATED FILE - do not edit by hand.
# Static snapshot regenerated by \`regen-shell-inits\`.
# ==============================================================================
# Snapshot of `pyenv init - fish` - avoids spawning pyenv on every shell start.
while set pyenv_index (contains -i -- "/Users/javier/.pyenv/shims" $PATH)
set -eg PATH[$pyenv_index]; end; set -e pyenv_index
set -gx PATH '/Users/javier/.pyenv/shims' $PATH
set -gx PYENV_SHELL fish
source '/usr/local/opt/pyenv/completions/pyenv.fish'
command pyenv rehash
function pyenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    source (pyenv "sh-$command" $argv|psub)
  case "*"
    command pyenv "$command" $argv
  end
end
